import { Box } from '@nextime-ui/react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'APP ROHAN',
  description: 'Generated by create next app'
}

export default function DashboardLayout({
  children
}: {
  children: React.ReactNode
}) {
  return <Box>pagina de login{children}</Box>
}
