import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'WWW Rohan',
  description: 'Generated by create next app'
}

export default function SiteLayout({
  children
}: {
  children: React.ReactNode
}) {
  return <div>{children}</div>
}
