name: Run E2E tests
on:
  deployment_status:
jobs:
  run-e2es:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Print BASE_URL
        run: echo "BASE_URL=$BASE_URL"
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: |
          DEPLOYMENT_URL=${{ github.event.deployment_status.environment_url }}
          PROJECT_NAME=$(echo "$DEPLOYMENT_URL" | sed -e 's#https://##' -e 's#-.*##')
          echo "Running E2E tests for project: $PROJECT_NAME"

          # Executar o script de teste E2E específico do projeto.
          pnpm run ${PROJECT_NAME}:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: List Playwright report directory contents
        run: ls -lah playwright-report/
